# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-12 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_ni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NI',
        ),
    ]
